project_id = "czswgpjjanllkmmwhmdh"

[api]
enabled = true
port = 54321

[db]
port = 54322

[auth]
enabled = true

[edge_runtime]
enabled = true
policy = "per_worker"

[functions.create-staff]
verify_jwt = true

[functions.update-staff-status]
verify_jwt = true